### ISSUE TITLE
Missing code for MIT model

### ISSUE THREAD

**Issue by LHDuan** [jimmy15923/mit#1]
It seems that the code for the MIT model is not included in the current repository. The code in the current repository is almost identical to BPNet and can only be used to train the segmentation model in the second stage and not to generate pseudo-labels for the training set. 
I wonder if the code for the MIT model will be available. 
Thank you.

**Comment by jimmy15923** [comment]
Hi! Thanks for your interest in our work. The full code will be available soon. Please stay tuned.

**Comment by doldol1234** [comment]
> Hi! Thanks for your interest in our work. The full code will be available soon. Please stay tuned.

hasaki

**Comment by cmhungsteve** [comment]
the full now is released now
